### ISSUE TITLE
Print Board posters to display at Mozfest

### ISSUE THREAD

**Issue by cassiemc** [mozilla/2015.mozillafestival.org#311]
A request from Surman. Might be a third poster to add. Getting clarity via email.

@Saallen can you clarify which two board posters? (I believe there were four total, but maybe only two that related to mozfest?)

@lovegushwa can you add assets here for the final print files and hopefully someone can help us get these printed/mounted at Ravensbourne.

@Saallen where will they be displayed/hung?

**Comment by lovegushwa** [comment]
I believe @marcwalsh will be doing some large format printing at Ravensbourne. Maybe we should start a ticket to track all large format printing.

**Comment by cassiemc** [comment]
Great idea @lovegushwa. I created https://github.com/mozilla/2015.mozillafestival.org/issues/315 to track it all. Might ultimately be better in a spreadsheet, I'd imagine @marcwalsh has his own system going on!

**Comment by thornet** [comment]
Tentative print run: 

* Evolution of Advocacy Program and Partnerships - A0
* Evolution of the Leadership Network - A0
* Mozfest 2010 - 2015 - A1
* "Building on MoFo's last five years, we will..." - A1

Waiting final feedback from @chrislarry33 and Mark.

**Comment by msurman** [comment]
I actually think we want:

1. All 8 posters same as we had at the board meeting.
2. Plus a 'centre column' of two or three posters w/ simple copy explaining what people are looking at and how to act.

-> e.g. on 2, A. "Mozilla 2020: we want your feedback on where we take Mozilla Foundation and MozFest over the next five years. Put up your sticky notes" B. list of our three main strategy points from slides. C. simple copy on how this all relates to MozFest (it's apex event in our effort to support a broader movement).

I'm not fussed on specifics. Maybe it's one or maybe it's three centre column slides. Whatever we do, it would be good for people to feel invited into the process we're in the middle of given how central MozFest is to both the history of this work (say thank you to people!) and the way we grow in the future.

Thoughts?

Maybe Kevin can help w/ copy, borrowing from board deck and

**Comment by thornet** [comment]
@lovegushwa could you get @marcwalsh large-format print tiles for the 8 posters from the board meeting? Note: we'll be using European paper formats. 

@KevZawacki would you mind taking a stab at the copy @msurman outlined? Think we won't need overly designed posters for this -- just take the board slide template and add text.

**Comment by msurman** [comment]
Also, @thornet: are you also printing bigger versions of the two timelines posters for your annotation exercise? I'm assuming those are separate.

**Comment by thornet** [comment]
Ah, good call. 

Yes, in addition to the 8 posters we'll need A0 size of the two timelines: 

* Evolution of Advocacy Program and Partnerships
* Evolution of the Leadership Network

And in case it's not already in the 8 posters, a poster version of this slide: 

* "Building on MoFo's last five years, we will..."

**Comment by cassiemc** [comment]
@lovegushwa Can you add the drive link to the posters here? I can help resize them to European sizes, just want to make sure I have the latest files.

**Comment by marcwalsh** [comment]
I'll be printing these next Wednesday onsite, the same as any other large format printing. It would be great to have everything in a drive folder so they are all in one place!

**Comment by lovegushwa** [comment]
@marcwalsh these are read to print at https://www.pixartprinting.co.uk/

A0 and 24x36" size, print one of each
https://drive.google.com/folderview?id=0B2qu3ExKWIlvd1RWdl82ZGhqMUU&usp=sharing

<img width="870" alt="screen shot 2015-10-29 at 9 56 35 pm" src="https://cloud.githubusercontent.com/assets/12228435/10838777/5f84702c-7e88-11e5-9c21-4f1cb796d169.png">

**Comment by KevZawacki** [comment]
@thornet Happy to help. Might need a little clarification on the project:

I'll pen copy that gives context to the eight board posters on display, correct? Is there a link to the eight posters, and how they'll be arranged?

**Comment by marcwalsh** [comment]
All ordered from Pixart - Will be Delivered Wednesday

**Comment by marcwalsh** [comment]
@lovegushwa - I have recieved the following errors back from Pixart.

<img width="609" alt="screen shot 2015-11-02 at 16 29 39" src="https://cloud.githubusercontent.com/assets/14007066/10887451/11d19f5e-817f-11e5-9154-b221f6ca2945.png">

It looks like the artwork is 1mm too big. The measurements need to be 91.6 x 61.1 and it's currently 91.6 x 61.2. 

I need this ASAP to match order deadlines.

**Comment by lovegushwa** [comment]
@marcwalsh will fix these and send you a new link right now.

**Comment by lovegushwa** [comment]
@marcwalsh ok the files are fixed. 
https://drive.google.com/folderview?id=0B2qu3ExKWIlvd1RWdl82ZGhqMUU&usp=sharing

**Comment by marcwalsh** [comment]
@lovegushwa - I'm still having the same issue with this. I can't change the order as it's been paid for. Are you able to try exporting them again. It's still saying:

Incorrect document dimensions
The file Mozilla_Board-posters_91.4x60.9cm-1.pdf you have sent measures 92.7x62.2 cm. To be able to proceed with printing we require the file to measure (including the bleed): 91.6x61.1 cm. Please upload an amended file.

**Comment by marcwalsh** [comment]
@lovegushwa - It's the same issue with all that size, the larger prints have gone through fine. I need these ASAP or they will not be delivered until the Friday.

**Comment by lovegushwa** [comment]
@marcwalsh I'll see if I can change these again right now.

**Comment by lovegushwa** [comment]
@marcwalsh try these: https://drive.google.com/file/d/0B2qu3ExKWIlvOHk3M1Z5dXRPdGM/view?usp=sharing

**Comment by marcwalsh** [comment]
Thanks @lovegushwa - Reuploaded to Pixart, will update you once the tests have run again.

**Comment by cassiemc** [comment]
@marcwalsh Good to close?
